# Temporary GitPage Host setup
title: CS230 Deep Learning
baseurl: "/cs230-2019-fall"
repository: "haossr/cs230-2019-fall"

# Theme settings
doks:
    baseurl: "https://cs230.stanford.edu"
    url: "https://hsheng.org"
    baseurl: "/cs230-2019-fall"
    color_theme: blue 
    header:
        logo:
            text: CS230
            image: true
        nav:
            - item_name: Syllabus
              item_url: '/syllabus'
            - item_name: Office Hours
              item_url: '/officehours'
            - item_name: Project
              item_url: '/project'
            - item_name: Section
              item_url: '/section'
            - item_name: Lecture
              item_url: '/lecture'
            - item_name: Blog
              item_url: '/blog'
            - item_name: FAQ
              item_url: '/faq'
    footer:
        content:
            logo:
                text: 
                image:
            copyright: Copyright &copy; 2019. - Stanford University <br>All rights reserved.
        social_list:
            # - network_name: facebook
            #   profile_url: '#'
            # - network_name: twitter
            #   profile_url: '#'
    google_analytics: UA-124237072-3
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
plugins_dir: ./_plugins
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md', 'scripts']
permalink: /:title/

# Course logistics
course: 
    quarter: 2019 Fall 
    time: Tue 9:00 AM - 10:20 AM  
    venue: NVIDIA Auditorium
    piazza: &pz 'https://piazza.com/class/k0rhx3vr6my26c' 
    queuestatus: 
        url: &qs 'https://queuestatus.com/queues/515'
        name: 'CS230 (2019 Fall)' 
    canvas: ''
    links:
        syllabus:
            icon: 
            content: Syllabus
            url: '/syllabus'
            external_url: false
        past-projects:
            icon:
            content: Past Projects
            url: '/past-projects'
            external_url: false
        project-2018-win:
            icon:
            content: Winter 2018
            url: '/past-projects/#winter-2018'
            external_url: false
        project-2018-spr:
            icon:
            content: Spring 2018
            url: '/past-projects/#spring-2018'
            external_url: false
        project-2018-fall:
            icon:
            content: Fall 2018
            url: '/past-projects/#fall-2018'
            external_url: false
        project-2019-win:
            icon:
            content: Winter 2019
            url: '/past-projects/#winter-2019'
            external_url: false
        project-2019-spr:
            icon:
            content: Spring 2019
            url: '/past-projects/#spring-2019'
            external_url: false
        video2018:
            icon: 
            content: Lecture videos (Fall 2018)
            url: '/lecture/'
            external_url: false 
        piazza:
            icon: 
            content: Piazza
            url: *pz
            external_url: true
        video:
            icon:
            content: Lecture videos (Canvas)
            url: 'https://canvas.stanford.edu/courses/100571/external_tools/3367'
            external_url: true
        queuestatus:
            icon:
            content: QueueStatus
            url: *qs
            external_url: true
    staff:
        - name: Andrew Ng
          type: Instructor
          url: https://www.andrewng.org/
          image: andrew.jpg 
        - name: Kian Katanforoosh
          type: Instructor
          url: https://www.linkedin.com/in/kiankatan/
          image: kian.jpg
        - name: Swati Dube 
          type: Coordinator 
          url: http://www.linkedin.com/in/swatidube/
          image: swati.jpg
        - name: Younes Mourri
          type: Course Advisor
          url: https://www.linkedin.com/in/younes-bensouda-mourri-8749b9a9/
          image: younes.jpg
        - name: Hao Sheng
          type: Head TA
          url: https://www.hsheng.org/
          image: hao.png
    
